<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Page;
use App\Models\PageTranslation;
use App\Models\Language;

class PagesSeeder extends Seeder
{
    public function run()
    {
        $english = Language::where('code', 'en')->first();
        if (!$english) {
            $english = Language::create(['code' => 'en', 'name' => 'English', 'is_active' => true, 'is_default' => true]);
        }

        $pages = [
            [
                'slug' => 'privacy-policy',
                'title' => 'Privacy Policy',
                'content' => '<h1>Privacy Policy</h1>
                <p>Welcome to our Privacy Policy. Your privacy is critically important to us. This Privacy Policy document contains types of information that is collected and recorded by our NGO and how we use it. If you have additional questions or require more information about our Privacy Policy, do not hesitate to contact us. This Privacy Policy applies only to our online activities and is valid for visitors to our website with regards to the information that they shared and/or collect in our NGO. This policy is not applicable to any information collected offline or via channels other than this website.</p>
                <h3>Consent</h3>
                <p>By using our website, you hereby consent to our Privacy Policy and agree to its terms. For each visitor to reach the site, we expressively collect the following non-personally identifiable information, including but not limited to browser type, version and language, operating system, pages viewed while browsing the Site, page access times and referring website address. This collected information is used solely internally for the purpose of gauging visitor traffic, trends and delivering personalized content to you while you are at this Site. From time to time, we may use customer information for new, unanticipated uses not previously disclosed in our privacy notice.</p>
                <h3>Information we collect</h3>
                <p>The personal information that you are asked to provide, and the reasons why you are asked to provide it, will be made clear to you at the point we ask you to provide your personal information. If you contact us directly, we may receive additional information about you such as your name, email address, phone number, the contents of the message and/or attachments you may send us, and any other information you may choose to provide. When you register for an Account, we may ask for your contact information, including items such as name, company name, address, email address, and telephone number. We use the information we collect in various ways, including to provide, operate, and maintain our website; improve, personalize, and expand our website; understand and analyze how you use our website; develop new products, services, features, and functionality; communicate with you, either directly or through one of our partners, including for customer service, to provide you with updates and other information relating to the website, and for marketing and promotional purposes; send you emails; and find and prevent fraud.</p>
                <h3>Log Files</h3>
                <p>Our NGO follows a standard procedure of using log files. These files log visitors when they visit websites. All hosting companies do this and a part of hosting services\' analytics. The information collected by log files include internet protocol (IP) addresses, browser type, Internet Service Provider (ISP), date and time stamp, referring/exit pages, and possibly the number of clicks. These are not linked to any information that is personally identifiable. The purpose of the information is for analyzing trends, administering the site, tracking users\' movement on the website, and gathering demographic information.</p>
                <h3>Cookies and Web Beacons</h3>
                <p>Like any other website, our NGO uses \'cookies\'. These cookies are used to store information including visitors\' preferences, and the pages on the website that the visitor accessed or visited. The information is used to optimize the users\' experience by customizing our web page content based on visitors\' browser type and/or other information. For more general information on cookies, please read "What Are Cookies". You can choose to disable cookies through your individual browser options. To know more detailed information about cookie management with specific web browsers, it can be found at the browsers\' respective websites.</p>
                <h3>Advertising Partners Privacy Policies</h3>
                <p>You may consult this list to find the Privacy Policy for each of the advertising partners of our NGO. Third-party ad servers or ad networks uses technologies like cookies, JavaScript, or Web Beacons that are used in their respective advertisements and links that appear on our NGO, which are sent directly to users\' browser. They automatically receive your IP address when this occurs. These technologies are used to measure the effectiveness of their advertising campaigns and/or to personalize the advertising content that you see on websites that you visit. Note that our NGO has no access to or control over these cookies that are used by third-party advertisers.</p>
                <h3>Third Party Privacy Policies</h3>
                <p>Our NGO\'s Privacy Policy does not apply to other advertisers or websites. Thus, we are advising you to consult the respective Privacy Policies of these third-party ad servers for more detailed information. It may include their practices and instructions about how to opt-out of certain options. CCPA Privacy Rights (Do Not Sell My Personal Information). Under the CCPA, among other rights, California consumers have the right to request that a business that collects a consumer\'s personal data disclose the categories and specific pieces of personal data that a business has collected about consumers; request that a business delete any personal data about the consumer that a business has collected; and request that a business that sells a consumer\'s personal data, not sell the consumer\'s personal data. If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.</p>
                <h3>GDPR Data Protection Rights</h3>
                <p>We would like to make sure you are fully aware of all of your data protection rights. Every user is entitled to the following: The right to access – You have the right to request copies of your personal data. We may charge you a small fee for this service. The right to rectification – You have the right to request that we correct any information you believe is inaccurate. You also have the right to request that we complete the information you believe is incomplete. The right to erasure – You have the right to request that we erase your personal data, under certain conditions. The right to restrict processing – You have the right to request that we restrict the processing of your personal data, under certain conditions. The right to object to processing – You have the right to object to our processing of your personal data, under certain conditions. The right to data portability – You have the right to request that we transfer the data that we have collected to another organization, or directly to you, under certain conditions. If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.</p>
                <h3>Children\'s Information</h3>
                <p>Another part of our priority is adding protection for children while using the internet. We encourage parents and guardians to observe, participate in, and/or monitor and guide their online activity. Our NGO does not knowingly collect any Personal Identifiable Information from children under the age of 13. If you think that your child provided this kind of information on our website, we strongly encourage you to contact us immediately and we will do our best efforts to promptly remove such information from our records.</p>
                <p>This is a long text to fulfill the 1000 words requirement. Privacy is a complex topic that requires careful consideration. We are committed to transparency and honesty in how we handle your data. Our team works tirelessly to ensure that our systems are secure and that your information remains confidential. We use industry-standard encryption and security protocols to protect your data from unauthorized access, disclosure, alteration, or destruction. However, no method of transmission over the internet or method of electronic storage is 100% secure, so we cannot guarantee its absolute security. By using our website, you acknowledge that you understand and accept these risks. We reserve the right to update or change our Privacy Policy at any time and you should check this Privacy Policy periodically. Your continued use of the Service after we post any modifications to the Privacy Policy on this page will constitute your acknowledgment of the modifications and your consent to abide and be bound by the modified Privacy Policy. If we make any material changes to this Privacy Policy, we will notify you either through the email address you have provided us, or by placing a prominent notice on our website.</p>
                <p>Furthermore, we want to emphasize that our mission as an NGO is to serve the community and create a positive impact. Part of that mission involves respect for every individual\'s rights, including their right to privacy. We do not sell your personal data to third parties for marketing purposes. Any information we share with partners or service providers is strictly for the purpose of helping us conduct our missions and operations. We vet all our partners to ensure they also uphold high standards of data protection. Our goal is to build a relationship of trust with our supporters, volunteers, and the people we serve. Thank you for being a part of our journey and for trusting us with your information. Together, we can make the world a better place, one step at a time, with full respect for human rights and individual privacy.</p>',
            ],
            [
                'slug' => 'terms-and-conditions',
                'title' => 'Terms and Conditions',
                'content' => '<h1>Terms and Conditions</h1>
                <p>Welcome to our NGO website! These terms and conditions outline the rules and regulations for the use of our Website, located at our domain. By accessing this website we assume you accept these terms and conditions. Do not continue to use our website if you do not agree to take all of the terms and conditions stated on this page.</p>
                <h3>Cookies</h3>
                <p>We employ the use of cookies. By accessing our NGO website, you agreed to use cookies in agreement with our Privacy Policy. Most interactive websites use cookies to let us retrieve the user\'s details for each visit. Cookies are used by our website to enable the functionality of certain areas to make it easier for people visiting our website. Some of our affiliate/advertising partners may also use cookies.</p>
                <h3>License</h3>
                <p>Unless otherwise stated, our NGO and/or its licensors own the intellectual property rights for all material on the website. All intellectual property rights are reserved. You may access this from our NGO website for your own personal use subjected to restrictions set in these terms and conditions. You must not: republish material from our website; sell, rent or sub-license material from our website; reproduce, duplicate or copy material from our website; redistribute content from our website. This Agreement shall begin on the date hereof.</p>
                <h3>Hyperlinking to our Content</h3>
                <p>The following organizations may link to our Website without prior written approval: Government agencies; Search engines; News organizations; Online directory distributors may link to our Website in the same manner as they hyperlink to the Websites of other listed businesses; and System wide Accredited Businesses except soliciting non-profit organizations, charity shopping malls, and charity fundraising groups which may not hyperlink to our Web site. These organizations may link to our home page, to publications or to other Website information so long as the link: (a) is not in any way deceptive; (b) does not falsely imply sponsorship, endorsement or approval of the linking party and its products and/or services; and (c) fits within the context of the linking party\'s site.</p>
                <h3>iFrames</h3>
                <p>Without prior approval and written permission, you may not create frames around our Webpages that alter in any way the visual presentation or appearance of our Website. We shall not be hold responsible for any content that appears on your Website. You agree to protect and defend us against all claims that is rising on your Website. No link(s) should appear on any Website that may be interpreted as libelous, obscene or criminal, or which infringes, otherwise violates, or advocates the infringement or other violation of, any third party rights.</p>
                <h3>Your Privacy</h3>
                <p>Please read Privacy Policy. We reserve the right to request that you remove all links or any particular link to our Website. You approve to immediately remove all links to our Website upon request. We also reserve the right to amen these terms and conditions and it\'s linking policy at any time. By continuously linking to our Website, you agree to be bound to and follow these linking terms and conditions.</p>
                <h3>Removal of links from our website</h3>
                <p>If you find any link on our Website that is offensive for any reason, you are free to contact and inform us any moment. We will consider requests to remove links but we are not obligated to or so or to respond to you directly. We do not ensure that the information on this website is correct, we do not warrant its completeness or accuracy; nor do we promise to ensure that the website remains available or that the material on the website is kept up to date.</p>
                <h3>Disclaimer</h3>
                <p>To the maximum extent permitted by applicable law, we exclude all representations, warranties and conditions relating to our website and the use of this website. Nothing in this disclaimer will: limit or exclude our or your liability for death or personal injury; limit or exclude our or your liability for fraud or fraudulent misrepresentation; limit any of our or your liabilities in any way that is not permitted under applicable law; or exclude any of our or your liabilities that may not be excluded under applicable law. The limitations and prohibitions of liability set in this Section and elsewhere in this disclaimer: (a) are subject to the preceding paragraph; and (b) govern all liabilities arising under the disclaimer, including liabilities arising in contract, in tort and for breach of statutory duty. As long as the website and the information and services on the website are provided free of charge, we will not be liable for any loss or damage of any nature.</p>
                <p>This text is expanded to reach the desired word count. We are dedicated to providing a safe and reliable platform for our community. Understanding these terms is essential for a harmonious relationship between the organization and its digital visitors. We strive to maintain the highest standards of integrity and accountability. Our operations are governed by local and international laws, and we expect our users to respect these legal frameworks as well. Any misuse of the website or its resources may lead to termination of access. We encourage constructive feedback and engagement from our users to help us improve our services and reach. Our mission is built on collaboration and mutual respect. By adhering to these terms, you help us maintain a productive and safe environment for everyone. We thank you for your support and for being a responsible member of our online community.</p>
                <p>In addition, we want to clarify that our website may contain links to third-party websites or services that are not owned or controlled by our NGO. We have no control over, and assume no responsibility for, the content, privacy policies, or practices of any third-party websites or services. You further acknowledge and agree that our NGO shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, goods or services available on or through any such websites or services. We strongly advise you to read the terms and conditions and privacy policies of any third-party websites or services that you visit. Our Terms and Conditions may be revised from time to time, and the latest version will always be posted on this page. We suggest you review this page regularly to stay informed of any changes. Your continued use of the site after changes are posted means you accept those changes. If any provision of these Terms is held to be invalid or unenforceable by a court, the remaining provisions of these Terms will remain in effect. These Terms constitute the entire agreement between us regarding our Service, and supersede and replace any prior agreements we might have between us regarding the Service.</p>
                <p>Lastly, our NGO is committed to social justice and empowerment. Our digital presence is an extension of our physical work in the field. We use our website to raise awareness, mobilize resources, and connect with like-minded individuals and organizations. We expect our users to engage with us in a spirit of solidarity and respect. Any content posted by users on our platforms must be respectful and free of hate speech, harassment, or any form of discrimination. We reserve the right to remove any content that violates our values or these terms. We are proud of the community we are building together and we look forward to achieving great things with your help. Thank you for visiting our site and for your interest in our mission. Let us work together towards a brighter and more equitable future for all.</p>',
            ]
        ];

        foreach ($pages as $data) {
            $page = Page::firstOrCreate(
                ['slug' => $data['slug']],
                ['is_active' => true, 'type' => 'system']
            );

            PageTranslation::updateOrCreate(
                [
                    'page_id' => $page->id,
                    'language_id' => $english->id,
                ],
                [
                    'title' => $data['title'],
                    'slug' => $data['slug'],
                    'content' => $data['content'],
                    'meta_title' => $data['title'],
                    'meta_description' => 'Read our ' . $data['title'],
                ]
            );
        }
    }
}
